import { MD3LightTheme } from 'react-native-paper';

export const appTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#6200ee',
    onPrimary: '#ffffff',
    primaryContainer: '#eaddff',
    onPrimaryContainer: '#21005d',
    secondary: '#03dac6',
    onSecondary: '#000000',
    secondaryContainer: '#cffff9',
    onSecondaryContainer: '#00362b',
    tertiary: '#018786',
    onTertiary: '#ffffff',
    tertiaryContainer: '#a4f1e9',
    onTertiaryContainer: '#00302b',
    error: '#cf6679',
    onError: '#ffffff',
    errorContainer: '#f9dedc',
    onErrorContainer: '#410e0b',
    background: '#fffbfe',
    onBackground: '#1c1b1f',
    surface: '#fffbfe',
    onSurface: '#1c1b1f',
    outline: '#79747e',
    outlineVariant: '#cac7d0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#313033',
    inverseOnSurface: '#f4eff4',
    inversePrimary: '#d0bcff',
    surfaceDim: '#ded9e1',
    surfaceBright: '#fffbfe',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f7f2fa',
    surfaceContainer: '#f3eef7',
    surfaceContainerHigh: '#ede7f0',
    surfaceContainerHighest: '#e8e3eb',
  },
};
